### ISSUE TITLE
`test_show_result_for_search_files` failing on Haiku (hrev52958, 64bit, Python 3.6.7)

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#104]
Here's an excerpt of the test log:

```

Fs.ss....ss.ss...E.
======================================================================
ERROR: test_show_result_for_search_files (tests.test_viewing_modes.TestViewingModes)
Testing def show_result_for_search_files. Search by extension.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/boot/home/Desktop/dev/count-files/tests/test_viewing_modes.py", line 131, in test_show_result_for_search_files
    self.generate_standard_file()
  File "/boot/home/Desktop/dev/count-files/tests/test_viewing_modes.py", line 32, in generate_standard_file
    with open(self.standard_file, 'w') as f:
AttributeError: 'TestViewingModes' object has no attribute 'standard_file'

======================================================================
FAIL: test_for_hidden (tests.test_argument_parser.TestArgumentParser)
Testing def main_flow.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/boot/home/Desktop/dev/count-files/tests/test_argument_parser.py", line 61, in test_for_hidden
    self.assertEqual(main_flow([self.get_locations('test_hidden_linux'), '-nr', '-t', '..']), 1)
AssertionError: 2 != 1

----------------------------------------------------------------------
Ran 21 tests in 0.096s

FAILED (failures=1, errors=1, skipped=7)
```

**Comment by NataliaBondarenko** [comment]
For BaseOS `test_viewing_modes.py` and `test_some_functions.py`  tests are not suitable.
Because the option to exclude hidden files and folders from counting or searching is not available (not implemented). It counts all files. In addition, standard files are defined for win, linux, darwin, ios.
The program can be used in those operating systems that are supported by Python. 
But we do not know in advance how hidden files are implemented there, case sensitivity, etc.
Therefore, some functions may not work, and you may need to write tests for this OS separately.
Test with `test_argument_parser.py` only now. Or manually.

**Comment by NataliaBondarenko** [comment]
Is it Unix-like?

**Comment by victordomingos** [comment]
Well, count-files tests/test_hidden_linux -fe .. -nr and count-files tests/test_hidden_linux -fe .. -nr were giving the same results, ignoring the hidden status of dotfiles. We'll probably have the same issue on any other unix related OS. Maybe we should make the default behaviour to consider dotfiles as hidden and create exceptions just for any operating systems that don't work like that (Windows comes to my mind, but there could be some others).

Meanwhile, I have updated the tests and (temporarily) the platform detection to treat Haiku as Linux. Now hidden files seem to be counted properly. Regarding Haiku, I also need to investigate if the OpenBFS file attributes include some other way to hide files and, if so, see if we are able to check it from Python (I believe there is also something to investigate on macOS on this regard).
