### ISSUE TITLE
Table issue

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#118]
> I also found that the table is not displayed if the terminal width is too small and the frequency is too long.  In `textwrap` `wrap(width=n)` does not accept negative values.
```
ext_col_width = min((term_width - freq_col_width - 5), <- here negative value
                        max_word_width,
                        MAX_TABLE_WIDTH)
```
> If devices with a small screen can have many files, we must deal with this.
total_occurrences = `10000000000000000000000000000`    :D

_Originally posted by @NataliaBondarenko in https://github.com/victordomingos/Count-files/issues/117#issuecomment-593650791_

**Comment by NataliaBondarenko** [comment]
If the ext_col_width <= 0, this causes an error
```
textwrap.py in _wrap_chunks raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width 0 (must be > 0)
```
If to do so:
```
# for case of small terminal width and long freq
if ext_col_width <= term_width:
    ext_col_width = term_width
```
then we will see a table, but not very readable.

A system can have many files:
https://stackoverflow.com/questions/466521/how-many-files-can-i-put-in-a-directory
But to get an error (on desktop), you need to significantly reduce the size of the terminal.

**Comment by victordomingos** [comment]
Hm. Just checked the maximum number of files for APFS, and apparently its 2^63, which means nearly 20 characters. A terminal width of 40 chars allows a maximum 15 characters long extension (5 extra chars are used for table drawing/formatting). 

I [added](https://github.com/victordomingos/Count-files/commit/e90ff180836bbe621a52767a30c1c104619f5575) a simple verification before drawing the table (`if term_width < (max_word_width + freq_col_width + 5)`), so that it only gets displayed if it fits the current terminal width. Maybe some of the tests will need to be updated.

I am not sure we have a real use case that would justify a more thoughtful implementation here. What is the minimum terminal width we should support? Currently I cannot spend much time in order to come out with a more robust solution, but I will be reviewing any eventual PRs, as usual.
