### ISSUE TITLE
Allow to search for files with no file extension 

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#12]
I propose using a dot (.) to mean no extension, when using `-fe` or `--file-extension`:

`countfiles.py --fe .`
`countfiles.py --file-extension .`

The above lines would list files like `.gitignore`, `Pipfile`.

**Comment by NataliaBondarenko** [comment]
I agree, we must do it. The parser does not process this parameter. But the user can search for files without an extension.

**Comment by NataliaBondarenko** [comment]
By the way, can we ask potential users their opinion on the actual parser functionality?
(something add, change, optimize). For example, in the Python Сommunity

**Comment by victordomingos** [comment]
Asking for feedback or even some user testing to help spot issues not found during development is fine. I wouldn’t start a chat room at this time for a project like this, though. I prefer to keep the discussion of features and bugs inside the issues section on GutHub. That way we have everything in one place. 

But I see no problem in asking also informally in social media and then open issues for relevant suggestions and bugs mentioned elsewhere.

**Comment by cgte** [comment]
Hello, the split ext should do the work fine.
I sent you the https://ybin.me/p/6056cb919b7ac01d#6TUJO4V8Zwcwg7fuL+g8znLANqG0SQCvKxlh5hll94w= pastebin on linkedin.
Here your code is doing too much : 
https://github.com/victordomingos/Count-files/blob/master/countfiles/utils/file_handlers.py#L11
you should use your helper to return the extension and let upper function decide if they process or not files with falsee extensions.

**Comment by victordomingos** [comment]
@cgte Nice work, very concise code, with a very different approach. I just think that it's not as readable (at least from my perspective). Having said that, my code is in fact needing a global cleanup. ;-) 

You are right about `get_file_extension()` doing too much. I just needed to write a `has_extension()`function that could very well be replaced by a slightly simpler `get_file_extension()`. I will have to merge those two functions soon.

**Comment by victordomingos** [comment]
@cgte, I think I get your point. My intention with `has_extension()` was to enable slightly shorter and more readable expressions (like in `if` clauses), but it was more of a quick way for me to better understand what I was writing in the upper function. I have meanwhile merged those two functions (`has_extension()` and `get_file_extension()`) into a single `get_file_extension()` that returns an empty (falsy) string when there is no extension.

Since we are not using a class for single files, I am not sure if you could/should make it a property.

I will be thankful if you could take another look and see the changes I made in this respect. Any further suggestions for improvement are always welcome.
