### ISSUE TITLE
Grouping with alphabetic order

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#120]
When using the `-g`/`--group` combined with `-alpha/`--sort-alpha`, the resulting list of frequencies should respect the alphabetical order inside each group. Something like this:

```
$ count-files -g -alpha

Recursively counting all files, ignoring hidden files and directories, in
/Users/victor/Downloads/Count-files-sortbygroup/tests


+ ARCHIVES(3)
   GZ: 3
+ DATA(4)
   DAT: 1
   JSON: 1
   XLSX: 2
+ DOCUMENTS(29)
   MD: 2
   TXT: 27
+ FONTS(1)
   WOFF: 1
+ PYTHON(14)
   PY: 14
+ OTHER(7)
   CSS: 1
   HTML: 1
   [no extension]: 5

  Found 58 file(s).
```

**Comment by NataliaBondarenko** [comment]
Updated in new PR: https://github.com/victordomingos/Count-files/pull/121

`[no extension]` on top.
Starts with a non-alphabetic character.

```
+ OTHER(7)
   [no extension]: 5
   CSS: 1
   HTML: 1
```

**Comment by victordomingos** [comment]
Technically, it it has no extension, it does not start :-). I don't know, I expected that entry to be the last when ordering alphabetically, since it's a special case, but that's not a very important detail.
