### ISSUE TITLE
Refactored as a package - some tasks pending

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#14]
- Update README.md with the correct instructions to run the package.
- Update README.md with installation guidelines.
- _Create a `setup.py` that includes the correct command-line entry point to run the application_ (maybe we'll need to rename the main module or create a separate won for that purpose).  **(I need help with this one!)**

**Comment by victordomingos** [comment]
@NataliaBondarenko, can you please help with the creation of the `setup.py` file? I would like to include it in version 1.4, but I confess it's the first time I will have one in one of my projects, so I am a bit afraid of screwing up right on the beginning :)

**Comment by victordomingos** [comment]
We have time. Version 1.4 should be released when that gets done and when there are no bugs in current functionality. But with no hurry. I will also try to dig a little into the documentation. ;-)

**Comment by NataliaBondarenko** [comment]
Suggestion: describe in README.md what exactly you need to do to install.
Since I already had a clone of the repository, I just added the ```file.pth``` with  ```\path\to-local-fork``` to the folder ```site-packages``` (temporarily add the path to the sys.path).
To make the installation with ```pip install -e``` I had to read the documentation, since I did not use this pip option before.

Installation
Info:
[pip install -e](https://pip.pypa.io/en/stable/reference/pip_install/#usage)
[pip uninstall](https://pip.pypa.io/en/stable/reference/pip_uninstall/#usage)
[csv-support](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support)
Examples:
```
pip [options] [-e] <vcs project url>
pip install -e git+https://github.com/victordomingos/Count-files.git#egg=foldername
pip uninstall countfiles
```
Expected result: а clone of the repository is created in ~/src/foldername and .pth files is added to site-packages.
```
pip [options] [-e] <local project path>
pip install -e \path\to-local-fork
pip uninstall -e \path\to-local-fork
```
Preconditions: а clone of the repository is already exist in \path\to-local-fork 
Expected result: .pth files is added to site-packages.

After installation ```python countfiles``` works.
After uninstallation, the file ```.pth```(in both cases) and folder ```src```  (in first case) remain.
Can I uninstall it incorrectly?

**Comment by NataliaBondarenko** [comment]
Maybe in README.md or in docs, usage demo:
```
>python countfiles -h
usage: countfiles [-h] [-a] [-alpha] [-nr] [-nt] [-fe FILE_EXTENSION] [-p]
                  [-ps PREVIEW_SIZE]
                  [path]

Count files, grouped by extension, in a directory. By default, it will count
files recursively in current working directory and all of its subdirectories,
and will display a table showing the frequency for each file extension (e.g.:
.txt, .py, .html, .css) and the total number of files found. Any hidden files
or folders (those with names starting with '.') are ignored by default.

positional arguments:
  path                  The path to the folder containing the files to be
                        counted.

optional arguments:
  -h, --help            show this help message and exit
  -a, --all             Include hidden files and directories (names starting
                        with '.')
  -alpha, --sort-alpha  Sort the table alphabetically, by file extension.
  -nr, --no-recursion   Don't recurse through subdirectories
  -nt, --no-table       Don't show the table, only the total number of files
  -fe FILE_EXTENSION, --file-extension FILE_EXTENSION
                        Search files by file extension (use a single dot '.'
                        to search for files without any extension)
  -p, --preview         Display a short preview (only available for text files
                        when using '-fe' or '--file_extension')
  -ps PREVIEW_SIZE, --preview-size PREVIEW_SIZE
                        Specify the number of characters to be displayed from
                        each found file when using '-p' or '--preview')
```

**Comment by NataliaBondarenko** [comment]
Note:
Linux, MacOS: ignored hidden files and folders (with names starting with ".")
Windows: hidden files are ignored (with the FILE_ATTRIBUTE_HIDDEN), ignoring hidden folders is not implemented now.

**Comment by victordomingos** [comment]
> After uninstallation, the file .pth(in both cases) and folder src (in first case) remain.
> Can I uninstall it incorrectly?

I didn't see a `.pth` file. Where is it located? Regarding deletion of the src folder, I am not sure it should be deleted by `pip`. What I would expect from a `pip uninstall count files` is the removal of `countfiles` from the python path, not the source. I believe the idea of using `pip install -e` is to allow us to keep editing and running a pre-release version during its development. The regular installation command for an end user would not include the `-e` option.

Therefore, we must specify the proper install/uninstall workflows for end-users and for developers. End users will probably be pip installing from Pypi (we need to experiment with Test Pypi first) and developers may prefer to pip install from a folder containing a cloned git repository, or using the single pip command you suggested.

**Comment by victordomingos** [comment]
> Linux, MacOS: ignored hidden files and folders (with names starting with ".")
> Windows: hidden files are ignored (with the FILE_ATTRIBUTE_HIDDEN), ignoring hidden folders is not implemented now.

@NataliaBondarenko, lets open an issue for that. I hadn't noticed that we were missing hidden folder verification in windows. Would you be able to add it in time for the current target release (no fixed deadline)?

**Comment by NataliaBondarenko** [comment]
.pth file in Python36\Lib\site-packages
So there will be two options for installation(for end-users and for developers).
I need some time to think about the hidden folders in Windows.

**Comment by victordomingos** [comment]
What is the full file name of that `.pth` file? What's the content of it?

**Comment by victordomingos** [comment]
I am not able to reproduce this issue here. I am being able to correctly install and uninstall by using these commands.

1. Change current working directory to the path containing the setup.py file, then run `pip3 install`.
```
$cd PROJECT_ROOT_PATH 
$pip3 install -e .
```
It installs `puremagic==1.4` and `argparse==1.4`if they're not present, as expected, and `countfiles` itself.

2. To uninstall, I just use:
```
$pip3 uninstall countfiles
Uninstalling countfiles-1.4:
  Would remove:
    /Library/Frameworks/Python.framework/Versions/3.7/bin/countfiles
    /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/countfiles.egg-link
Proceed (y/n)? y
  Successfully uninstalled countfiles-1.4
```

**Comment by NataliaBondarenko** [comment]
```
C:\Users\Net\Count-files>pip3 install -e .
Obtaining file:///C:/Users/Net/Count-files
Requirement already satisfied: puremagic==1.4 in c:\users\net\appdata\local\programs\python\python36\lib\site-packages (from countfiles==1
.4)
Requirement already satisfied: argparse in c:\users\net\appdata\local\programs\python\python36\lib\site-packages (from puremagic==1.4->cou
ntfiles==1.4)
Installing collected packages: countfiles
  Running setup.py develop for countfiles
Successfully installed countfiles
```
Created:
site-packages\countfiles.egg-link
site-packages\easy-install.pth
scripts\countfiles-script.py
scripts\countfiles.exe
C:\Users\Net\Count-files\countfiles.egg-info (folder)
```
C:\Users\Net\Count-files>pip3 uninstall countfiles
Uninstalling countfiles-1.4:
  c:\users\net\appdata\local\programs\python\python36\lib\site-packages\countfiles.egg-link
  c:\users\net\appdata\local\programs\python\python36\scripts\countfiles-script.py
  c:\users\net\appdata\local\programs\python\python36\scripts\countfiles.exe
Proceed (y/n)? y
  Successfully uninstalled countfiles-1.4
```
easy-install.pth and countfiles.egg-info (folder) don't removed
But it's not a problem.

**Comment by victordomingos** [comment]
Maybe that's how it's intended to be, but I confess I don't know. The egg-info, I believe, is expected to be removed manually. The other file, I have never came across it before.
