### ISSUE TITLE
Hidden files and directories detection does not work on Windows

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#16]
Currently, the detection of hidden files and directories is based only on the .filename convention used in Unix-like operating systems. That is not the case in Windows, where files with names starting with a dot are not necessarily expected to be hidden and where hidden files can have names starting with any other of the allowed characters.

In order to implement this feature on windows, we will need first to detect the family of the host operating system and then adjust accordingly. In principle, it should be pretty easy by using something like:

```
import os
if os.name == 'nt':
```
Related docs: https://docs.python.org/3/library/os.html?highlight=os%20name#os.name

To determine if a file or directory is hidden on Windows, we can use the `stat.FILE_ATTRIBUTE_HIDDEN` flag returned by `os.stat()`:

https://docs.python.org/3/library/stat.html
https://msdn.microsoft.com/en-us/library/windows/desktop/gg258117.aspx

However, I have a little problem here, as I don't have easy access to a windows machine to test if it will work as expected...

**Comment by NataliaBondarenko** [comment]
I have Windows 8.1
directory .git is hidden
with default recursion
```python countfiles ~/Count-files/.git -a``` counts well
```python countfiles ~/Count-files/.git``` return 'Oops! We have no data to show...'
```python countfiles ~/Count-files/``` return number of files less then ```python countfiles ~/Count-files/ -a```

**Comment by NataliaBondarenko** [comment]
I created another hidden folder and file. Really: does not work (:

**Comment by victordomingos** [comment]
Here's a relevant discussion about it on StackOverflow:

https://stackoverflow.com/questions/284115/cross-platform-hidden-file-detection

I think the best approach would be to define a function that would detect if file is hidden in a cross-platform way, testing at least for the dot character on Unix-like systems and for the HIDDEN attribute on Windows.

**Comment by victordomingos** [comment]
Just added a preliminary version of is_hidden(), based on one of those replies on StackOverflow. We'll need to adjust testing code accordingly, and also run some tests and the necessary changes on iOS (I am almost sure that Pythonista does not include ctypes and there will occur an ImportError).

**Comment by victordomingos** [comment]
@NataliaBondarenko, I have accepted your last pull request and added a separate condition for macOS on `is_hidden_file_or_dir()` (at this time, doing the same kind of hidden file verification as in linux, but letting the door open for further eventual development of more a complete macOS hidden file verification).

Can you please give us an update on the current status on Windows? Is everything working, or is there anything failing?

**Comment by NataliaBondarenko** [comment]
Those functions that I added were tested in Windows.
Part that does not work is search by ```-fe```:
get: ctypes.ArgumentError: argument 1: <class 'TypeError'>: Don't know how to convert parameter 1
Counting all files is work.

**Comment by victordomingos** [comment]
Hm... I am afraid I am not able to help with that one. It seems to be something undocumented by the Python team, probably because it belongs more properly to the Windows developer documentation. In case we don't find a solution for that, i would try to create a minimal code example to reproduce the same issue and then submit it in a new question on StackOverflow. Do you agree?

**Comment by NataliaBondarenko** [comment]
It's work fine separatly with Python 3 and Windows:
```
try:
    import ctypes
except:
    pass


def _has_hidden_attribute(filepath):
    """
    Adapted from Jason R. Coombs (https://stackoverflow.com/a/6365265/6167478)
    """
    try:
        attrs = ctypes.windll.kernel32.GetFileAttributesW(filepath)
        assert attrs != -1
        result = bool(attrs & 2)
    except (AttributeError, AssertionError):
        result = False
    return result

print(_has_hidden_attribute('C:/some/path/file.txt'))
```
Something is wrong in the call / execution process.
need to understand how this works, what it returns, if you plan to use it somewhere.

**Comment by victordomingos** [comment]
Do you mean the above sample works ok on Windows and does not raise any exception?

**Comment by NataliaBondarenko** [comment]
Yes, and correctly identifies hidden files and folders.

**Comment by victordomingos** [comment]
Please try to catch an exception in the import statement. Something like this.

```
try:
    import ctypes
except Exception as e:
    print(e)
```

**Comment by victordomingos** [comment]
So, if I understand correctly, the above code sample works separately, but in our file it’s generating an error?

**Comment by NataliaBondarenko** [comment]
It's  works separately. For Python 3 ```bool(os.stat(filepath).st_file_attributes & stat.FILE_ATTRIBUTE_HIDDEN)``` do the same

**Comment by victordomingos** [comment]
@NataliaBondarenko, I did a small cleanup, merging duplicate functionality and removing unused code. The old `is_hidden()` and `_has_hidden_attribute()` were deleted, since we already have `is_hidden_file_or_dir()`. Please check if it works ok on windows, or if there is still anything failing.
