### ISSUE TITLE
Allow to choose inclusion or exclusion of hidden files/directories when using --file-extension or -fe

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#17]
Following the pattern of all command line arguments being optional and freely combinable, I think `countfiles`should allow to choose inclusion or exclusion of hidden files/directories when using `--file-extension` or `-fe`, by adding the `-a`or `--all` switches.

Example:
```
countfiles -fe html -a ~/Documents
countfiles -file-extension html --all ~/Documents
```

**Comment by NataliaBondarenko** [comment]
I will conduct experiments with Windows. But I do not promise that it's fast.
What files are usually hidden? Which extension or name?

**Comment by victordomingos** [comment]
I am not sure if there is some extension that is frequently present in hidden files on windows. We could do tests with regular files manually hidden

https://www.lifewire.com/what-is-a-hidden-file-2625898

**Comment by victordomingos** [comment]
Do you mean inverting the defaults, I mean, by default searching with inclusion of hidden files and having a command-line switch to turn off hidden files? 

I think we should keep hiding hidden files by default, and only showing them when the user selects `-a` or `--all`. And if possible extend that behaviour to all the application features (recursive/non-recursive, file search, file count...).
