### ISSUE TITLE
Missing tests – get_files_without_extension()

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#20]
The function `get_files_without_extension()` now has a `recursive` keyword argument, so it would need to get its test suite updated.

**Comment by NataliaBondarenko** [comment]
Hello! The test suite has been updated. It looks like the new features work fine.
But for the correct inclusion or exclusion of hidden files / directories, we need to know which the operating system is used. I'll see what I can do with Windows.

**Comment by victordomingos** [comment]
@NataliaBondarenko, can we close this issue, or is there still anything left?

**Comment by NataliaBondarenko** [comment]
Yes we can.
