### ISSUE TITLE
dev branch

### ISSUE THREAD

**Issue by NataliaBondarenko** [victordomingos/Count-files#26]
We also need to create a branch for development.For experiments with new and old features.  If the changes are successful, they will be transferred to the branch master(production).

**Comment by victordomingos** [comment]
That’s one way. The other way would be to have releases as stable, useable versions, and the main branch being developed as usual. The current setup has the advantage of being a little less complex. I am not entirely sure we have a need for a separate dev branch.

**Comment by NataliaBondarenko** [comment]
? Release as source code or/and stable version branches, like [django](https://github.com/django/django/branches)

**Comment by victordomingos** [comment]
The way that seems better for me, given the size of the project, is to keep the current `master` branch and just to create short-lived feature branches that end up with a new release. We can call the branch by the target version (e.g. `v.1.5 dev`). Then, at the moment of the release all changes of that branch are merged into the master, the old dev branch is removed and a new branch is created for the next target release (e.g. `v.1.6 dev`). The advantage of this branching model would be to have always a stable `master`, where a simple `git clone` would get the code for the most recent stable release.

What do you think about it?

**Comment by NataliaBondarenko** [comment]
OK
