### ISSUE TITLE
Licensing update

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#27]
Up until now, this project has been made available under Creative Commons Attribution Share Alike 4.0. It's a fairly permissive license that allows a wide range of use cases, including commercial use and code modifications, provided that it retains a license and copyright notice, any code changes are clearly documented and redistribution of derivative work must be released under the same or a similar license. 

However, this license was not made for software and is not recommended for that purpose. So, I am looking for another license that is more suitable for software and that keeps about the same level of freedom. Any suggestions?

**Comment by NataliaBondarenko** [comment]
Something simple, for example, MIT. [choosealicense](https://choosealicense.com)

**Comment by victordomingos** [comment]
Yeah, I always liked the conciseness of MIT license. Good idea.
