### ISSUE TITLE
While recursively scanning in large directories there is no feedback

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#34]
Scanning a large number of files recursively in all subdirectories can take some minutes but current the user gets no feedback during that time. There should be some [optional?] indicator that the application is still working in those cases. For instance, printing a total file/folder count every few seconds, or after processing a few thousand files, before generating and printing the final report.

**Comment by NataliaBondarenko** [comment]
It would be user-friendly.

**Comment by victordomingos** [comment]
Also, I have been thinking about the possibility of making some changes in `search_files()` in order to allow us to print the paths being found while still searching. Instead of letting the user waiting for, let's say, 5 or 10 minutes, it would show each found file immediately. Maybe converting this function into a generator, or by using separate threads (1 thread for file searching, 1 thread for printing) and a FIFO queue between them.

**Comment by victordomingos** [comment]
We have progress some progress in this area! It took just a few changes to convert `search_files()` into a generator, instead of building and returning a big list. I did a few tests just to see if it worked and to assess the performance impact and I have some good news:

* Doing `python3 -m countfiles -fe . -a /` (searching for all files without extension) in one Mac with SSD used to take between 1m45s and 1m55s, and required about 88MB of RAM. The user needed to wait around 1 minute and a few seconds before any path was printed to the screen.
* Doing the same with the new generator-based version shaves 5 to 10 seconds (not that much), BUT... it takes only about 25MB of RAM (yeah, less than one third) and the results are shown immediately, as soon as they are found, with no wait time.

Nice, isn't it? :)

The bad news is that the tests are now failing, because now the function does not return a list, it just yields a new file path each time it is called.

**Comment by victordomingos** [comment]
I noticed that when searching for all files on Mac (for instance without extension), it takes a lot more time when printing the file paths to the screen. Turning off the list (`countfiles -fe . -nl -a /`) takes about 0m56s, while with the list it takes about 1m36s. Its a machine with a fast SSD, but on slower computers it could make a bigger difference. Wondering if splitting it into two threads sharing a FIFO queue would make it snappier...

**Comment by victordomingos** [comment]
Performance improvement migrated to issue #56. The rest is complete, so we'll close this one.
