### ISSUE TITLE
Huge spike in memory usage when searching with preview (large files)

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#36]
In some cases, the application seems to freeze while trying to generate a file preview for a big file (for instance, `countfiles -fe . -p ~/`). In my case, it happened with mailbox files that had about 1.2GB in size. Memory usage by the Python process spiked to about 10GB and there was no visible output during several minutes, when there should be shown a short text preview for that file. Doing a simple `$head FILEPATH` on the shell seems to open the file correctly and print the expected file contents.

Possible culprit seems to be `generate_preview()` (to begin, shouldn't we be opening the file in a context manager?). We need to check its behaviour and change it as needed. Is it reading the whole file content into a bytes object before slicing the first part? If so, lets make sure it reads only the required amount of information from the file.

**Comment by victordomingos** [comment]
It seems to have been solving by the recent changes (probably by not doing previews for binary files). Closing this issue.

**Comment by NataliaBondarenko** [comment]
Hello!
I looked at the source code of the functions that are used to display the preview.
pathlib.py
```
    def open(self, mode='r', buffering=-1, encoding=None,
             errors=None, newline=None):
        """
        Open the file pointed by this path and return a file object, as
        the built-in open() function does.
        """
        if self._closed:
            self._raise_closed()
        return io.open(str(self), mode, buffering, encoding, errors, newline,
                       opener=self._opener)

    def read_bytes(self):
        """
        Open the file in bytes mode, read it, and close the file.
        """
        with self.open(mode='rb') as f:
            return f.read()

    def read_text(self, encoding=None, errors=None):
        """
        Open the file in text mode, read it, and close the file.
        """
        with self.open(mode='r', encoding=encoding, errors=errors) as f:
            return f.read()
```
[https://docs.python.org/3/library/io.html#high-level-module-interface](https://docs.python.org/3/library/io.html#high-level-module-interface)
```
io.open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)
This is an alias for the builtin open() function.
```
def read_bytes() and def read_text() -> return f.read()
As I understand it, the entire file is read.
in def generate_preview():
```
excerpt = f.read_text(errors="replace")[0:max_size].replace('\n', ' ')
excerpt = f.read_bytes()[0:max_size]
```
This displays the part of the entire file that has already been read.

[https://docs.python.org/3.3/tutorial/inputoutput.html#methods-of-file-objects](https://docs.python.org/3.3/tutorial/inputoutput.html#methods-of-file-objects)
f.read() and f.readlines() can take the value "size".

Path.open(mode='r', buffering=-1, encoding=None, errors=None, newline=None)
Please try this with that big mailbox file:
```
 # or f.readline() with loop
 # or print(f.readlines(3))
from pathlib import Path
p = Path('path/to/file')
with p.open(mode='rb') as f:
    print(f.read(200))
```

**Comment by victordomingos** [comment]
I am experimenting with this and apparently it is indeed a good option! Showing previews for all files without extension in one HDD based computer took almost 5GB of RAM, and total 72 minutes. The same operation with a preliminar version using the approach above took 18 times less memory (270MB), and just 47 minutes. I will do some cleanup and commit what I have.

**Comment by NataliaBondarenko** [comment]
47 minutes! Do you want to read all the files on your computer?

**Comment by victordomingos** [comment]
It’s a stress test, to check the memory impact on more extreme conditions. You never know what the user will do, and `countfiles / -a` is probably one of the first experiments some people would do. ;)

Besides, I have no idea of which file was being problematic with the previews.

**Comment by victordomingos** [comment]
Closing this issue, as the memory leak seems to be solved by now.
