### ISSUE TITLE
Add a new option to list all files, regardless of their extension

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#37]
Similar to `countfiles -fe`, but allowing to list any files, with or without extension in their file names.

E.g.:

```
countfiles -l DIRPATH
countfiles --list-files DIRPATH
```

The other parameters (recursion/no-recursion, include-hidden) would be in place as usual.

**Comment by NataliaBondarenko** [comment]
We can reorganize the display of results in this way:

A) File counting by extension
- table (listing file extension frequencies) - enabled by default
  - Sort alphabetically
  - Sort by frequency - enabled by default
- total (just a summary)
- list (--list-files, list of all found file paths, list with file size info)
   - withoutl file preview

B) File searching by extension
 - list (--list-files, list of all found file paths, list with file size info)- enabled by default
   - Optional file preview - not enabled by default
   - Optional size specification for file preview
- total (just a summary)

instead of "-nt" and "-nl" there will be common arguments "-t"(--total) and "-l"(--list-files)
Used functions:
```
if extension:
    if args.preview and args.list_files:
        if not is_supported_filetype(extension):
            parser.exit(status=0, message=not_supported_type_message)
    if args.list_files:
        # getting data list
        data = (f for f in search_files(dirpath=location, extension=extension,
                                        include_hidden=include_hidden, recursive=recursive))
        # display result in chosen view mode
        len_files = show_result_for_search_files(files=data, list=True,
                                                 preview=args.preview, preview_size=args.preview_size)

    # total
    if args.total:
           # or use def search_files() or make a function that will only count the number of files,
           # and not return file paths.
          data = (f for f in search_files(dirpath=location, extension=extension,
                                        include_hidden=include_hidden, recursive=recursive))
          
          len_files = show_result_for_search_files(files=data, list=False,
                                                 preview=args.preview, preview_size=args.preview_size)
```
```
if all extensions

if args.list_files:
        if args.preview and not args.no_list:
            if not is_supported_filetype(extension):
                parser.exit(status=0, message=not_supported_type_message)
        # getting data list
        data = (f for f in search_files(dirpath=location, extension='',
                                        include_hidden=include_hidden, recursive=recursive))
        # display result in chosen view mode
        len_files = show_result_for_search_files(files=data, list=True,
                                                 preview=False, preview_size=args.preview_size)

if args.table:
    data = count_files_by_extension(location, include_hidden=include_hidden, recursive=recursive)
     if sort_alpha:
          show_2columns(sorted(data.items()))
     else:
           show_2columns(data.most_common())

if args.total:
        data = count_files_by_extension(location, include_hidden=include_hidden, recursive=recursive)
        return show_total(data)
```

**Comment by victordomingos** [comment]
So, if I understood correctly, you propose that we add a new option (like `-l` or `--list-files`) that would be common to both files counting and file searching. That option would therefore be off by default (i.e. the user will only see the list of file paths when the command `--list-files` is included. One inconvenient of that approach is that for a large number of files, we get (again) no feedback by default to the user during that process (but that could be mitigated with some other visual feedback).

Another option would be to keep the file list by default, and add it to the file counting routine, before displaying the summary table. This would have the advantage of giving instant feedback to the user, by using the generator approach we already have in place for the file searching. The current `-nl`or `--no-list`option would allow to turn off the file list in both cases.

Do you think it makes sense to include a table for file searching? It would have only one line plus the total, I see no need for that, and in fact unless we have a good reason, I prefer the current, more "natural-language" like, approach. One possible justification for that approach would be to stop thinking of 2 separate groups/features (counting and searching) and have a single feature (search and count) with all the options, being one of them the option to filter by extension (i.e., the current `-fe`).

What do you think?

**Comment by NataliaBondarenko** [comment]
Now:
A) File counting by extension
default: table (no feedback)
no-table (no feedback) - total number

- also a list can be here

B) File searching by extension
default: list (feedback)
no-list (no feedback) - total number and file sizes info

- tables are not required here

A) File counting by extension
This option is possible:
For the table/no-table, you may need to add feedback.
But if the user chose a table, then perhaps it is not worth printing a list.
We take an already existing generator.
We use the def count_file_extensions() separately to print the found extensions. This returns a counter for def show_2columns() and def show_total().
```
def count_file_extensions(files, feedback: bool):
    from collections import Counter
    counters = Counter()
    for f in files:
        extension = get_file_extension(f)
        if extension == '.':
            extension = '[no extension]'
        counters[extension] += 1
        if feedback:
            print(extension)
    return counters
```
in def main_flow():
```
    # ...or do other stuff, i.e., counting files.
    # data = count_files_by_extension(location, include_hidden=include_hidden, recursive=recursive)
    data = (f for f in search_files(dirpath=location, extension=extension,
                                        include_hidden=include_hidden, recursive=recursive))

    data = count_file_extensions(data, feedback=True)

    if show_table:
        if sort_alpha:
            show_2columns(sorted(data.items()))
        else:
            show_2columns(data.most_common())
        # it returns None
    else:
        return show_total(data)
```
print for table:
```
Recursively counting all files, ignoring hidden files and directories, in C:\Users\Net/Count-files/tests

txt
py
txt
. . .
[no extension]
txt
txt
xlsx
pyc
pyc
pyc
pyc
 EXTENSION      | FREQ.
----------------+-------
 txt            |    13
 py             |     6
 [no extension] |     5
 pyc            |     4
 gz             |     3
 md             |     2
 html           |     1
 json           |     1
 css            |     1
 woff           |     1
 dat            |     1
 xlsx           |     1
----------------+-------
 TOTAL:         |    39
----------------+-------
```
print for no-table:
```
Recursively counting all files, ignoring hidden files and directories, in C:\Users\Net/Count-files/tests

txt
py
txt
py
. . .
py
json
md
gz
css
gz
txt
gz
woff
[no extension]
py
dat
txt
[no extension]
txt
[no extension]
txt
txt
xlsx
pyc
pyc
pyc
pyc
Total number of files in selected directory: 39.
```
B) File searching by extension
list:
feedback is present
no-list
If the user does not want the list, then just print a notification like "you need to wait".
And give a beep when the data is ready ( joke :) .
I was thinking about how to make a progress indicator. But in this case we need to know the amount of work.

**Comment by victordomingos** [comment]
I don't like the list of extensions as a way to provide feedback. I would prefer the full file path, or current directory path, followed by files contained in it. Another option, compatible with most terminals, would be to print all the file paths to the same console line, by using the carriage return (something like `print(filepath, end="\r")`). In most systems, this would take just one or two lines in the screen, rapidly changing through each file found. In a few rare cases (like in Pythonista for iOS), the `end="\r")` part may happen to be ignored, printing each file path into a new line. No big deal. In the end, that text line would be cleared and replaced by the final table and/or total.

I still think it would be a nice addition to have the option to list all files, regardless of their extension.

I don't think it would be easy to add a progress indicator here, at least one that would show the current stage, because to know in advance the amount of work, we would need to traverse the filesystem twice. The alternative would be to display the current folder/file, as described above, or an indeterminate progress indicator (something like spinning bars, blinking dots...). Anyway, the current folder/file seems to be the better option, as it shows the computer working as goes through files and displays some potentially useful information on which part of the filesystem is being scanned. 

One issue that may arise with this approach, however, is when we have a long wait without any files being found. That won't be a problem if we choose to print always the current working directory (even if no matching files were found there) and the matching files as they are found. Not sure it it will slow down significantly the operation, but if it has just a little impact, I think if can become more user friendly.

**Comment by NataliaBondarenko** [comment]
Well, then:
```
def count_file_extensions(files, feedback: bool):
    from collections import Counter
    counters = Counter()
    for f in files:
        extension = get_file_extension(f)
        if extension == '.':
            extension = '[no extension]'
        counters[extension] += 1
        if feedback:
            print(f)
    return counters
```

**Comment by victordomingos** [comment]
Yes, but in order to make each file path replace the previous one, as discussed above:

```
        if feedback:
            print(f, end="\r")
```

**Comment by NataliaBondarenko** [comment]
on Windows does not work.
You can do it.

**Comment by victordomingos** [comment]
What happens on Windows?

**Comment by NataliaBondarenko** [comment]
cmd -> prints the all list( filepath \ n filepath ...)
PowerShell-> prints the all list, if it's big; if the list is small then prints in one line.

**Comment by victordomingos** [comment]
Can you post a screenshot or a copy of the output?

**Comment by victordomingos** [comment]
Also, can you please test also with `end=""`?

**Comment by NataliaBondarenko** [comment]
print(f, end="\r")
print()one line, last line looks weird: 
```
C:\Users\Net/Desktop\Новая папка\hidden_py\test_file.pycxooth.LNK.txthon-35.pycpycypgSet 65500.epsview.jpg
```
```
C:\Users\Net\Count-files>python countfiles ~/Desktop

Recursively counting all files, ignoring hidden files and directories, in C:\Users\Net/Desktop

C:\Users\Net/Desktop\Новая папка\hidden_py\test_file.pycxooth.LNK.txthon-35.pycpycypgSet 65500.epsview.jpg
 EXTENSION      | FREQ.
----------------+-------
 py             |   298
 txt            |    48
 . . .
 png            |     1
 LNK            |     1
----------------+-------
 TOTAL:         |   436
----------------+-------
```
many files:
```
C:\Users\Net\Count-files>python countfiles ~/.PyCharmCE2016.3

Recursively counting all files, ignoring hidden files and directories, in C:\Users\Net/.PyCharmCE2016.3

C:\Users\Net/.PyCharmCE2016.3\config\plugins\BashSupport\classes\com\ansorgit\plugins\bash\documentation\SystemInfopageDocSource$MyCapturingProces
C:\Users\Net/.PyCharmCE2016.3\config\plugins\BashSupport\classes\com\ansorgit\plugins\bash\editor\BashSpellCheckingSupport$BashHeredocTokenizer.cl
. . . prints all paths
EXTENSION                       | FREQ.
---------------------------------+-------
 py                              |   551
 class                           |   548
. . .
dll                             |     1
 x                               |     1
---------------------------------+-------
 TOTAL:                          |  2331
---------------------------------+-------
```

**Comment by NataliaBondarenko** [comment]
print(f, end="")
prints all the paths in one heap.
C:\Users\path/file.txtC:\Users\path\file.pyC:\Users\. . .

**Comment by victordomingos** [comment]
Ok. I think I know what’s going on. The carriage return character (“\r”) moves the carret to the left. But then we get a shorter file path and part of the previous text is not completely overwritten. So, we need to make sure that the remaining text is overwritten by spaces.

Please try this:

```
print("\r"+f.ljust(400), end="")
```

**Comment by NataliaBondarenko** [comment]
```
print("\r"+f.ljust(400), end="")
```
prints all paths
It is enough to work. Tomorrow I'll think about it and see examples on the Internet. Good night.

**Comment by victordomingos** [comment]
Ok. I did a small change based in the latest codebase. Please check it out. I did not add the feedback argument, though.

**Comment by victordomingos** [comment]
@NataliaBondarenko, I think all stuff from this conversation is done and working as expected by now, right? I just want to make sure that there is nothing left, before closing the issue.

**Comment by NataliaBondarenko** [comment]
The argument ```no-list``` was added to search for files by a certain extension. The table is used to display the results of counting all files.
If we use ```def search_files```, we can also add a list to count all the files. But ```def count_files_by_extension``` is a little faster.
```def search_files``` can be optimized, but I still need to check it.
If we do not add the display list to the counting of files, we can close it.

**Comment by victordomingos** [comment]
Hm.. It works nice as it is. Maybe we could add something to the search arguments syntax, for the sake of completeness. I mean, we are abele to search files without extension, files with a specific extension, but we don't have a way to search for files with any extension (all extensions). I think we could add the option to search with `-fe ..` (2 dots) with the meaning of "all files, with any extension". What do you think, @NataliaBondarenko?

**Comment by victordomingos** [comment]
@NataliaBondarenko, I think that by now there is nothing left to do from this issue. It's all done, right?

**Comment by NataliaBondarenko** [comment]
It's all done.
