### ISSUE TITLE
Filenames that start with dot (hidden files on Unix-like systems) should not be treated as extensions

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#4]
For instance, `.gitignore`should be treated as a filename, not an extension.

Also, we should be making use of the existing `os.path.splitext()` instead of regular string splitting, as it probably will avoid some errors. That method already takes care of the `.name` issue mentioned above.

**Comment by NataliaBondarenko** [comment]
It will be useful. Similar function is available at pathlib.Path().suffix  (or .suffixes)

**Comment by victordomingos** [comment]
This one is already fixed in the current version.
