### ISSUE TITLE
changelog.txt is out of date

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#46]
We need to summarize the main changes since v.1.3, and try to wrap this version for PyPI submission. 

The current feature set seems to be pretty stable by now, so with a few adjustments I think we could advance to the TestPyPI stage.

**Comment by NataliaBondarenko** [comment]
Let's skip the long and detailed descriptions. I propose to describe the features of the last stable version and that's it.

**Comment by NataliaBondarenko** [comment]
- updated folder structure and refactored as package
- updated preview for text files, added list of supported types
- added support for case sensitiveness
- added feedback
- added total counting option
- added full support for handling hidden files and folders
- tests for different os
- updated main functions:
   - with generators(def search_files)
   - with list comprehensions (def count_files_by_extension)
- added docs and readme EN, PT, RU
- added RTD
- added support for search/count files without extension(`.`) or all files(`..`)

**Comment by victordomingos** [comment]
Seems fine. ;)
Please expand RTD, though.
Logs are already in place, or it's still a WIP?

**Comment by NataliaBondarenko** [comment]
I added a new source for the https://countfiles.readthedocs.io/en/latest/
I will deal with logs today or tomorrow.
if I can not finish the logs, then it will be without them.

**Comment by victordomingos** [comment]
Are logs needed for an utility like this? What specific use case do you have in mind?

**Comment by NataliaBondarenko** [comment]
There is no pressing need for this. Logs may be required to store an error history, for example, to detect recurring failures. The user can report an error later. 

without a logger:

```
def exceptions_decorator(func):
    """Registration and interception of the main exceptions.

    :param func: executable function
    :param logger: the logging object
    :return:
    """
    @wraps(func)
    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except KeyboardInterrupt:
            print('The execution of the program was interrupted.')
        except Exception:
            # print traceback
            print(traceback.format_exc())
            # print message
            print('Sorry, an error occurred while retrieving data.\n'
                  f'You can report a problem at {BUG_REPORT_URL}')
    return wrapper
```
What do you think about it?

**Comment by victordomingos** [comment]
I have just updated changelog.txt with your suggestions. I removed the last line (logs). We can add it later if it makes its way to this release.

**Comment by victordomingos** [comment]
Seems ok to me.
