### ISSUE TITLE
Make the display of file size in file path lists optional

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#51]
I have been thinking on making optional the file size display for each listed file path. It would allow to use this utility to build simple lists of paths separated by newlines that can be useful in some contexts. The adicional info (file size) may affect the ability for this list to be used by other tools.

`-hs ` 
`--hide-file-sizes`

**Comment by NataliaBondarenko** [comment]
Hello! Done with `--file-sizes`
