### ISSUE TITLE
Try to improve performance while searching files with feedback or list display

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#56]
I noticed that when searching for all files on Mac (for instance without extension), it takes a lot more time when printing the file paths to the screen. Turning off the list (`countfiles -fe . -nl -nf -a /`) takes about 1m05s, while with the list (`count-files -fe . / -a`)  it takes about 1m40s, an increase of about 50%. Without list but with feedback (`count-files -fe . / -a -nl`), it takes 1m30s (a bit more than without feedback, but less than with the full list). 

These tests were conducted in a machine with a fast SSD, but on slower computers it could make an even bigger difference. 

Wondering if splitting it into two threads sharing a FIFO queue would make it significantly snappier without making the codebase a lot more complex.

**Comment by NataliaBondarenko** [comment]
`--no-list` is not exist :)

**Comment by victordomingos** [comment]
Haha... it existed at that time :)
