### ISSUE TITLE
Images for Readme

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#59]
Let's upload here the screenshots we will be using on our readme.

**Comment by victordomingos** [comment]
![count-files_screenshot1](https://user-images.githubusercontent.com/18650184/42160179-29998a52-7dee-11e8-9813-b8594e50fe77.png)

**Comment by NataliaBondarenko** [comment]
![win_count](https://user-images.githubusercontent.com/23127253/43415315-efbb706e-943d-11e8-9ccc-e575eeb54fcc.png)

**Comment by NataliaBondarenko** [comment]
```
Search for files on the USB flash drive.
```
![win_search](https://user-images.githubusercontent.com/23127253/43424303-a755bb76-9457-11e8-8d54-5cda76d1417b.png)

**Comment by NataliaBondarenko** [comment]
![linux_search](https://user-images.githubusercontent.com/23127253/43489095-79ac37cc-9524-11e8-8ede-cad25ca962b4.png)

**Comment by NataliaBondarenko** [comment]
I want to add links in examples. images should be stored somewhere.
![count_linux_mint](https://user-images.githubusercontent.com/23127253/45508149-c1dbf880-b79c-11e8-9814-ba04f4c00b90.png)

**Comment by NataliaBondarenko** [comment]
![count_windows](https://user-images.githubusercontent.com/23127253/45508316-2b5c0700-b79d-11e8-9e4d-8675fd1e3c0a.png)

**Comment by NataliaBondarenko** [comment]
![count_linux_mint_fe_txt](https://user-images.githubusercontent.com/23127253/45508325-36169c00-b79d-11e8-81e2-0d01b7e1ab70.png)

**Comment by NataliaBondarenko** [comment]
![search_linux_mint_with_args](https://user-images.githubusercontent.com/23127253/45508392-60685980-b79d-11e8-95a6-95f068f14ce6.png)

**Comment by NataliaBondarenko** [comment]
![total_windows](https://user-images.githubusercontent.com/23127253/45508405-6fe7a280-b79d-11e8-9db9-c81b0116ed1d.png)

**Comment by victordomingos** [comment]
I initially started using images uploaded into an issue as a hack to allow using them in the readme. Is this enough?
