### ISSUE TITLE
Improve recursion when ignoring hidden directories

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#6]
As suggested by Daniel Baboiu @ Linkedin:

> Recursive search does a full recurse of hidden directories, only to ignore all files in them.

What would be the best way to do recursion and skip hidden directories?

**Comment by NataliaBondarenko** [comment]
What is the problem? Will it work slowly?

**Comment by victordomingos** [comment]
I guess that’s what he was concerned about. With a relatively small number of files and folders, and with a fast SSD, it performs nicely, but in slower HDD computers any performance improvement can be very significant. I did not investigate yet what are the options for a faster file lookup and recursion, neither their impact on performance...

**Comment by victordomingos** [comment]
Just did a few changes concerning recursion. Not sure if it could be further optimized, but I am closing this one.
