### ISSUE TITLE
To be considered: can we simplify this by using a dictionary instead of a class?

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#7]
As suggested by Daniel Baboiu @ Linkedin:

> You don't need a full class for the counter. Just use a dictionary with extensions as keys (best method for storing data), then (if you need sorting) convert it to a list of tuples, and sort with the standard list methods.

To be considered: can we simplify our code by following this suggestion?

**Comment by NataliaBondarenko** [comment]
In fact, class collections.Counter is a dict subclass. So, class WordCounter is a wrapper around another class. In general, we can get rid of it.
in main.py:
```fc = WordCounter()``` replace with ```counter = Counter()``` and use it's methods directly.
Sort_by_frequency: counter.most_common(), sort_by_word: sorted(counter.items()) and so on.

**Comment by victordomingos** [comment]
I plan to dedicate one release just to improvements on code readability and bug fixes, with no new features. Maybe 1.5 or 1.6. It may be considered then.
