### ISSUE TITLE
If there is a very long extension, the table won't display properly

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#72]
When counting files, it there happens to be a file that as a dot and then a very long text, it may not fit the terminal window, making the output look weird. Also, such a very long extension shouldn't probably be considered an extension. Usually file name extensions are small abbreviations or small words. While some filesystems allow for longer file names, that could in theory have long extensions, there is probably no use case for very long file extensions as a way to classify file types.

Therefore, I suggest we limit the extension size to a certain maximum number of 65 characters, in order to accommodate even some large numbers in the table without the need to truncate text. Any file extension longer that the specified maximum length would be treated as `[no extension]`.

**Comment by NataliaBondarenko** [comment]
this is not a bug, it's a feature :)
Using the program, the user can find any extension, even such a long or strange.

I suggest not to change the core functionality, especially before the release.
And if you still change, then we need to warn the user that the files with long extensions refer to files without an extension.
files with such long extensions may will be few, so in most cases the table will look like usual.

As far as I understand, the problem is not in the work of the program, but in showing results.
Then why do not we change the results display?
This is one of the possible options. There is a truncation of the text, but the full title is given below.
 Here I made approximate indents - .ljust(6), .ljust(10)
But the size of the table, for example, may depend on the width settings of the terminal.
```
def show_2columns(data: List[tuple]):
    if not data:
        print("Oops! We have no data to show...\n")
        return

    total_occurences = 0
    for word, freq in data:
        total_occurences += freq

    total_occurences_width = len(str(total_occurences))
    if total_occurences_width < 5:
        total_occurences_width = 5

    header = f" {'INDEX'.ljust(6)} | {'EXTENSION'.ljust(10)} | {'FREQ.'.ljust(total_occurences_width)} "
    sep_first = (6 + 2) * '-'
    sep_left = (10 + 2) * '-'
    sep_center = "+"
    sep_right = (total_occurences_width + 2) * '-'
    sep = sep_first + sep_center + sep_left + sep_center + sep_right
    print(header)
    print(sep)
    notes = []
    for index, (word, freq) in enumerate(data):
        if len(word) <= 10:
            print(f" {str(index).ljust(6)} | {word.ljust(10)} | {str(freq).rjust(total_occurences_width)} ")
        else:
            notes.append((index, word, freq))
            print(f" {str(index).ljust(6)} | {word[0: 7]}... | {str(freq).rjust(total_occurences_width)} ")

    print(sep)
    line = f" {' '.ljust(6)} | {'TOTAL:'.ljust(10)} | {str(total_occurences).rjust(total_occurences_width)} "
    print(line)
    print(sep + "\n")
    if notes:
        print('Long extensions:')
        for note in notes:
            print(f'Index: {note[0]}, Extension: {note[1]}, Occurences: {note[2]}')
    return

```
output looks like this, only with the preservation of appropriate indentation:

 INDEX  | EXTENSION  | FREQ.
--------+------------+-------
 0          | LNK        |     4
 1          | URL        |     1
 2          | SEARCHC... |     1
--------+------------+-------
            | TOTAL:     |     6
--------+------------+-------

Long extensions:
Index: 2, Extension: SEARCHCONNECTOR-MS, Occurences: 1

**Comment by victordomingos** [comment]
The are a few options:

1. Truncate long file extensions (as you suggested) to terminal width;
2. Adapt the table to allow wrapping to more than one line;
3. Ignore very long file extensions (as I had suggested).

I think that while long file extensions may hardly be seen as "extensions", solutions number 1 and number 2 are in fact more elegant. The number 2 (allowing text wrapping) would be a little better, in my opinion, as it would not require adding a third column to the table and a second text section below with the long form. However, it would require more complex code to generate the table, which is a small  inconvenience. There are packages out there that may do that easily, but it would imply adding external dependencies.

So, i think we can take the code you suggested and merge it with a few small adjustments:

1. INDEX column: right justify the numeric contents, like in the FREQ. column.
2. EXTENSION column: make it adjust to the current terminal width, when possible.
3. EXTENSION column: use Unicode Character "…" (U+2026) (at leas on mac, it seems to take only 1 character width, instead of 3 characters). 
4. Long extensions section: replace index by " #" (with one or two spaces at the beginning) and change order, trying to keep vertical alignment and making it as short as possible:

We have this:
```
Index: 1600, Extension: 010EEA7FB467F15E0E10F0093205526F18087C470E, Occurences: 1
```

I suggest something like this:
```
  #1600: 1 occurrence of ext.: 010EEA7FB467F15E0E10F0093205526F18087C470E
```

**Comment by NataliaBondarenko** [comment]
we must think about how best to make a responsive table.
what packages?

**Comment by victordomingos** [comment]
2 years ago I have used terminaltables in an earlier, text-based, version of PT Tracking:

https://pypi.org/project/terminaltables/

But there may be other packages that are more robust. Not sure. It’s a easy way to replace our function, but on the other hand it’s an external dependency. It should not be a big problem, as it’s not something that most users will have installed as a dependency for other applications. It should be pure-python.

**Comment by victordomingos** [comment]
There are a couple other packages that allow easy creation of text based tables. As long as they're pure python with no dependencies and it works well both on desktop and iOS, I see no big deal adding it as a dependency. Most packages won't include a way to specify the maximum width, but we can do it by wrapping the text for each cell.

**Comment by NataliaBondarenko** [comment]
There is such a variant of text transfer on several lines:
def grouper from https://docs.python.org/3/library/itertools.html#itertools-recipes
```
def grouper(iterable, n, fillvalue=None):
    """Collect data into fixed-length chunks or blocks"""
    # grouper('ABCDEFG', 3, 'x') --> ABC DEF Gxx"
    args = [iter(iterable)] * n
    return zip_longest(*args, fillvalue=fillvalue)
```
```
def show_2columns(data: List[tuple]):
    if not data:
        print("Oops! We have no data to show...\n")
        return

    total_occurences = 0
    for word, freq in data:
        total_occurences += freq

    total_occurences_width = len(str(total_occurences))
    if total_occurences_width < 5:
        total_occurences_width = 5

    header = f" {'INDEX'.ljust(6)} | {'EXTENSION'.ljust(10)} | {'FREQ.'.ljust(total_occurences_width)} "
    sep_first = (6 + 2) * '-'
    sep_left = (10 + 2) * '-'
    sep_center = "+"
    sep_right = (total_occurences_width + 2) * '-'
    sep = sep_first + sep_center + sep_left + sep_center + sep_right
    print(header)
    print(sep)
    notes = []
    for index, (word, freq) in enumerate(data):
        if len(word) <= 10:
            print(f" {str(index).ljust(6)} | {word.ljust(10)} | {str(freq).rjust(total_occurences_width)} ")
        else:
            new_word = list(grouper(word, 10, ''))
            notes.append((index, word, freq))
            print(f" {str(index).ljust(6)} | {''.join(new_word[0])} | {str(freq).rjust(total_occurences_width)} ")
            for item in new_word[1:]:
                print(f" {' '.ljust(6)} | {''.join(item)} | {' '.rjust(total_occurences_width)} ")

    print(sep)
    line = f" {' '.ljust(6)} | {'TOTAL:'.ljust(10)} | {str(total_occurences).rjust(total_occurences_width)} "
    print(line)
    print(sep + "\n")
    if notes:
        print('To long extensions:')
        for note in notes:
            print(f'Index: {note[0]}, Extension: {note[1]}, Occurences: {note[2]}')
    return

```
output
![variant](https://user-images.githubusercontent.com/23127253/44864810-413fd700-ac89-11e8-8626-52a96520ddb8.png)

**Comment by NataliaBondarenko** [comment]
Some points need to be worked out. We can also do without an "index" column.

**Comment by NataliaBondarenko** [comment]
or without `|`
![variant_1](https://user-images.githubusercontent.com/23127253/44865492-21a9ae00-ac8b-11e8-8742-2c1e17ba04f1.png)

**Comment by NataliaBondarenko** [comment]
![variant_2](https://user-images.githubusercontent.com/23127253/44865810-07bc9b00-ac8c-11e8-9381-0bd2026fa64a.png)

**Comment by victordomingos** [comment]
We only need the index column if we truncate the text. If we just translineate it, then there’s no need for the index and the legend.

How is that grouper different from textwrap()?

**Comment by NataliaBondarenko** [comment]
In this case, the string is cut into segments of no more than a given length, then they are printed in a loop.
If the ` textwrap` is easier, then do it.

**Comment by NataliaBondarenko** [comment]
```
    if not data:
        print("Oops! We have no data to show...\n")
        return

    total_occurences = 0
    for word, freq in data:
        total_occurences += freq

    total_occurences_width = len(str(total_occurences))
    if total_occurences_width < 5:
        total_occurences_width = 5

    header = f" {'EXTENSION'.ljust(10)} | {'FREQ.'.ljust(total_occurences_width)} "
    sep_left = (10 + 2) * '-'
    sep_center = "+"
    sep_right = (total_occurences_width + 2) * '-'
    sep = sep_left + sep_center + sep_right
    print(header)
    print(sep)
    for word, freq in data:
        if len(word) <= 10:
            print(f" {word.ljust(10)} | {str(freq).rjust(total_occurences_width)} ")
        else:
            print(f" {word[0: 10]} | {str(freq).rjust(total_occurences_width)}")
            new_text = textwrap.wrap(word[10:], width=10, initial_indent=' ' * 2, subsequent_indent=' ' * 2)
            for item in new_text:
                print(f" {item.rjust(10)} | {' '.rjust(total_occurences_width)}")
    print(sep)
    line = f" {'TOTAL:'.ljust(10)} | {str(total_occurences).rjust(total_occurences_width)} "
    print(line)
    print(sep + "\n")
    return
```
![variant_3](https://user-images.githubusercontent.com/23127253/44874039-8c1a1880-aca2-11e8-9b38-98dc7e0c163c.png)

nice? :)

**Comment by victordomingos** [comment]
Cool! Now it only needs to adjust to the terminal width :)

**Comment by NataliaBondarenko** [comment]
column_size = TERM_WIDTH // 4
25% ?

**Comment by victordomingos** [comment]
I would say let it expand as long as there is space available, counting with the other elements (spacers and columns).

**Comment by victordomingos** [comment]
After merging #74, I tested on my iPhone:

```
[~/Documents]$ count-files.py 
 Recursively counting all files,
ignoring hidden files and directories,
in /private/var/mobile/Containers/Shared
/AppGroup/F3C0E711-6D38-4FDF-81F2-DC3B97
E4E9F1/Pythonista3/Documents
_                                                                             
 EXTENSION     | FREQ. 
---------------+-------
 PNG           | 20950 
 PY            | 10894 
 JPG           |  7654 
 HTML          |  6737 
 CSS           |  4246 
 [no extension |  3593
             ] |      
 SVG           |  2960 
 MD            |  1813 
 JSON          |  1611 
 TXT           |  1099 
 TEX           |     9 
 XSL           |     9 
 2             |     8 
 COMPRESSIMAGE |     8
      S-BACKUP |      
 SQLITE        |     7 
 P             |     7 
 PDF           |     6 
 FSH           |     6 
 POT           |     6 
 EXE           |     6 
 SVGZ          |     6 
 PSD           |     6 
 PXM           |     6 
 CONF          |     5 
 HTC           |     5 
 STY           |     5 
 0             |     5 
 TPL           |     5 
 BAT           |     5 
 CAST          |     5 
 DAT           |     4 
 MARKDOWN      |     4 
 PEM           |     4 
 (...)
---------------+-------
 TOTAL:        | 67363 
---------------+-------

[~/Documents]$ 
```

It does not extend to the space needed and available.

**Comment by victordomingos** [comment]
![Image](https://i.imgur.com/QDdnrDT.jpg)

**Comment by NataliaBondarenko** [comment]
make EXT_COLUMN_WIDTH larger

**Comment by NataliaBondarenko** [comment]
if TERM_WIDTH <= 100:
    EXT_COLUMN_WIDTH = TERM_WIDTH // 2  (or some number)
else:
    EXT_COLUMN_WIDTH = TERM_WIDTH // 6

**Comment by victordomingos** [comment]
Actually, I think the solution needs to be something else. The table should extend to the detected terminal width. The extensions and frequency columns should expand as needed, according to the length of the longest string they need to display in one line. 

So, the extension width will depend on 3 variables:

1. The length of the longest string it will display in a single line: it should grow to that size.
2. The width of frequency column (the variable `total_occurences_width` + spaces and separators): the extensions column should leave space for that column;
3. The terminal width: the total length of the line (extensions + freq. + spacers + separators) should be about two characters shorter than the terminal width.

**Comment by victordomingos** [comment]
Let’s think on some examples:

On my iPhone I have about 60 characters wide, with very small font. I could easily have 40 characters. On a big Mac, I will have more that 120, but most of the time it will be between 80 and 100. The table should adapt to make use of a bigger screen and to be usable in a smaller console. It should never be smaller than needed if there is a long text line to display.

**Comment by victordomingos** [comment]
If I have some time, I will try some modifications on this.

**Comment by victordomingos** [comment]
Commit 290fdb1 should solve this. Please take a look. The bad news is that we now have another failing test, once again :)

**Comment by NataliaBondarenko** [comment]
we defined `MAX_TABLE_WIDTH = 80`
Yes, we need to add a long extension to the tests. Only after the final version of the function is completed. I have already rewrote the tests 3 times :)

**Comment by victordomingos** [comment]
Actually, the seems to be a little bug introduced in __main__.py, line 258:

```
    max_word_width = len(max(data.keys()))
```

You see, we are using `max()` on strings, and it does not check for string length, but maximum alphabetical character.

```
>>> a = "01234567890"
>>> b = "a123"
>>> c = "123a"
>>> max(a,b,c)
'a123'
```

I have fixed it by changing that line:

```
    max_word_width = max(map(len, data.keys()))
```

 Should work as expected, now.
