### ISSUE TITLE
Incorrect error messages

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#77]
```
$ count-files.py optimize-images/ -a -fe png -p
 Recursively searching all files with (case-insensitive) extension .png,
including hidden files and directories, in optimize-images/
Sorry, there is no preview available for this file type. You may want to try again without preview.
This is the list of currently supported file types for preview: c, css, html, js, json, md, py, txt.
Previewing files without extension is not supported. You can use the "--preview" argument together with the search for all files regardless of the extension ("--file-extension .."). In this case, the preview will only be displayed for files with a supported extension.
```

**Comment by NataliaBondarenko** [comment]
Incorrect error messages? A more detailed explanation is needed.
By the way, what is it? `import ui` and `import console` in settings. Is it a dependency?

**Comment by victordomingos** [comment]
Sorry, I was on iPhone, but wanted to make sure we woudn't forget to see this.



> $ count-files.py optimize-images/ -a -fe png -p
>  Recursively searching all files with (case-insensitive) extension .png,
> including hidden files and directories, in optimize-images/
> Sorry, there is no preview available for this file type. You may want to try again without preview.
> This is the list of currently supported file types for preview: c, css, html, js, json, md, py, txt.
**_> Previewing files without extension is not supported. You can use the "--preview" argument together with the search for all files regardless of the extension ("--file-extension .."). In this case, the preview will only be displayed for files with a supported extension._**


Here, we are searching for files with PNG extension and asking to display a file preview. This file format does not have a file preview available, so it should display only the first part of the message. The last part should not be displayed in this case, since we are not searching for files without extension.


> By the way, what is it? import ui and import console in settings. Is it a dependency?

These are two modules that come built into Pythonista on iOS.  They allow to access some platform-specific settings and features, like in this case adjusting the console font and measuring the console width (for some reason, the `shutil`method wasn't enough). They're not an external dependency, because they are only used on iOS/Pythonista, and they come preinstalled.
