### ISSUE TITLE
Improve text preview (or disable) text preview for binary files

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#8]
Displaying a text preview for non-text files seems to be not that useful, as the content shown most times won't even be readable. So, It seem to me that there are two options for improvement:

A. Detect if it is a text file (how?) and only show a preview if that's the case.
B. Detect the file type (maybe using [puremagic](https://pypi.org/project/puremagic/) and display useful metadata (for instance, image size) if available.

**Comment by NataliaBondarenko** [comment]
How about that:
Determine the list of extensions for which preview is available
Check the user-selected extension. If it in list then - preview

**Comment by victordomingos** [comment]
Seems a good idea. 

There are some known extensions that can be previewed as text, but we will also need to put in place some kind of check to distinguish between text and binary files, as a fallback after checking for known formats. Here is an implementation by Andrew Dalke: https://www.safaribooksonline.com/library/view/python-cookbook-2nd/0596007973/ch01s12.html

Also, puremagic may be useful here.
https://pypi.org/project/puremagic/

For PDF files, we could use PyPDF2 to get the number of pages (`PdfFileReader.getNumPages()`):
https://pythonhosted.org/PyPDF2/PdfFileReader.html#PyPDF2.PdfFileReader.getNumPages


For images, PIL/Pillow can provide image size info:
http://pillow.readthedocs.io/en/5.1.x/reference/Image.html

For zip and gzip archives, we could display the number of compressed items. Here’s a useful StackOverflow on that subject: 
https://stackoverflow.com/questions/31124670/how-to-programmatically-count-the-number-of-files-in-an-archive-using-python?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

For audio files, we could display duration, bitrate, sample rate, artist, album, if available. Maybe this package can help:
https://pythonhosted.org/hsaudiotag3k/usage.html#available-attributes

Regarding these new dependencies, as long as they are also available or installable on Pythonista for iOS, we can add them.

**Comment by victordomingos** [comment]
I just discovered this. Possible to `puremagic` (file type detection), seems to have been updated more recently, but still not sure if the codebase is more mature.

https://github.com/floyernick/fleep-py

**Comment by victordomingos** [comment]
Having gone through `pure magic`documentation and code, it seems to me that it offers pretty easy path for file type identification:

1. Use `puremagic` to identify filetype (mime).
2. If mime starts with `text/`, show a simple text preview.
3. If it doesn't, try to use use another available preview method.
4. If no preview method is available for the detected mime, or if no mime was detected, display a simple `"No text preview available."` message.

**Comment by victordomingos** [comment]
Having gone through pure magicdocumentation and code, it seems to me that it offers a pretty easy path for file type identification:

1. Use `puremagic` to identify filetype (mime).
2. If mime contains `text/`, show a simple text preview.
3. If it doesn't, try to use use another available preview method.
4. If no preview method is available for the detected mime, or if no mime was detected, display a simple `"No text preview available."` message.

Trying to make an initial "skeleton" of this, that should be committed soon.

**Comment by NataliaBondarenko** [comment]
You found a lot of useful information.
Maybe it's a lazy method, but why not temporarily do it like this:

add in def get_files_by_extension:

```
                if preview:
                    try:
                        print('text')
                        print(f.read_text()[0:preview_size].replace('\n', ' '))
                    except:
                        print('bytes')
                        print(f.read_bytes()[0:preview_size])
                    print('–––––––––––––––––––––––––––––––––––')
                    #print(f.read_text(errors="replace")[0:preview_size].replace('\n', ' '))
                    print("–––––––––––––––––––––––––––––––––––\n")
```
for ```python countfiles.py --file-extension png  --preview --preview-size 500``` it is return:
```
bytes
b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00Z\x00\x00\x012\x08\x06\x00\x00\x00zx\xc7\x81\x00\x00\x00\tpHYs\x00\x00\x0b\x13\x00\x00\x0
b\x13\x01\x00\x9a\x9c\x18\x00\x00\x01niTXtXML:com.adobe.xmp\x00\x00\x00\x00\x00<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0
">\n   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">\n      <rdf:Description rdf:about=""\n            xmlns:dc="http:
//purl.org/dc/elements/1.1/">\n         <dc:subject>\n            <rdf:Bag/>\n         </dc:subject>\n      </rdf:Description>\n   </rdf:R
DF>\n</x:xmpmeta>\n\xe5?\rA\x00\x00\x03\xeaIDATx\x9c\xed\xdd\xc1r\x1bU\x10@\xd1\x1e\x03\x81\xa2\xe0\xff?\x146@\xc2c\x91R\xc1\xc2\x89\x8c5\
xbe<\x0f\xe7\xac]\x1d\xe5f\xfc,M[\xd113?\xcf\xcc\xef\xc3\x9b\xfavff\xad\xf5\xdb\xa3'

```

**Comment by victordomingos** [comment]
Not a bad idea!

In fact, I have been testing both `puremagic` and `fleep`, and apparently text file detection is not included at all, which means that `.py` or `.html` are not detected. So, the approach I was getting into was to keep a list of known text types and check if the file extension was in that list. If it wasn't, it would use `puremagic` to determine the filetype. In the end, if no suitable preview method was found, then bytes preview could be displayed. 

I am still not sure if we really need to detect filetypes, as the user has to indicate the file extension. Maybe we can use your approach and improve upon it: 

1. try first to display a known text or binary format, using one of the available preview methods (e.g. for img, pdf...) – the file format could be inferred from the file extension provided by the user;
2. if it fails or the file format is unknown, do the text/bytes sequence you described above.

**Comment by victordomingos** [comment]
Using Pandas on this project falls a little out of its proposed scope, as it would make it incompatible with Pythonista for iOS. Unless it is added as an optional requirement and everything else works fine even when Pandas is not installed.

Regarding Standard Library (or easily installable pure-python packages), you are right. We have tools that can allow some interesting previews, and no time limits. It can be added one at a time.
