### ISSUE TITLE
Test runner fails

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#82]
I get a traceback while running this:

```
$ python3.7 test_runner.py 
Traceback (most recent call last):
  File "test_runner.py", line 2, in <module>
    from tests.test_argument_parser import TestArgumentParser
ModuleNotFoundError: No module named 'tests.test_argument_parser'
```

**Comment by NataliaBondarenko** [comment]
The test works as usual. You just can not start it. The module itself is in place?

**Comment by victordomingos** [comment]
In another Mac, I couldn't reproduce the issue. In the computer that produces the error above, if I run it with Python 3.6, it's runs as expected. The file `test_argument_parser.py` is in the `tests` folder. It's a bit strange.

**Comment by victordomingos** [comment]
Tested again in with pipenv (removing old Pipfile and Pipfile.lock, that I think shouldn't be needed at this time) and all tests pass. Maybe its something with this specific machine.
