### ISSUE TITLE
How to count symbolic links and windows shortcuts?

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#89]
Example with symbolic link
![link_img](https://user-images.githubusercontent.com/23127253/45588682-19a36c80-b921-11e8-80d3-b8eb3ff6f1f9.png)

Example with Windows shortcut
![win_sh](https://user-images.githubusercontent.com/23127253/45588775-101b0400-b923-11e8-9692-e242e13339c8.png)

Should I pay attention to such files or count them on a par with others?

_Originally posted by @NataliaBondarenko in https://github.com/victordomingos/Count-files/issues/84#issuecomment-421604292_

**Comment by NataliaBondarenko** [comment]
yes, they are treated as files.

**Comment by victordomingos** [comment]
Let's keep it this way, so. Unless we have a good reason to change, I think it works as expected as we have it.
