### ISSUE TITLE
Help system - improve readability

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#96]
Some parts of the help system are too long and maybe can be made shorter, now that we have the ability to specify help topics or keywords. Instead of a long page, we may add a few lines indicating the presence of other related subsections or pages. 

It applies also to the new help system, for instance when using `count-files -ah docs`. Ideally each subpage should fit in a 25 or 40 lines terminal display, unless we have a very good reason to keep all the text it in a single help page.

Also: wouldn't it be better to use "topic(s)" instead of "keyword(s)"? It seems to be a bit more clear.

@NataliaBondarenko

**Comment by NataliaBondarenko** [comment]
Help system is almost ready. It will be necessary to make some changes when I add the ability to search by simple regex (startswith, endswith, contain). Then we will need to check the help text for inconsistencies and typos.
