### ISSUE TITLE
Switching to classes

### ISSUE THREAD

**Issue by NataliaBondarenko** [victordomingos/Count-files#99]
I propose to change the structure of the program. We can use the class to work with the OS.

For example: WindowsOS and UnixOS. Methods to identify hidden files and folders are different for each OS. 
As far as I understand, there may still be changes for macOS (`/Volumes/MobileBackups`).
In addition, if we add the skip of hidden files for Windows, it is not necessary for other operating systems.

We can create classes with methods that will be called the same, but will have a slightly different implementation. And use the corresponding class instance in the parser (depending on the current OS).
This will allow us to make specific changes for the OS without dividing the program into different versions for different OS.
If you need to change the check of hidden files for macOS, you can create a separate class and override the method in it. At the same time, for other Unix, nothing will change.

**Comment by victordomingos** [comment]
Not sure if it's needed and worth the effort. Can you please propose an outline of the alternative code structure you have in mind (modules/classes/methods)?

**Comment by NataliaBondarenko** [comment]
```
class BaseOS(object):
    def get_file_extension
          ...
    def search_files
          ...
    def count_files_by_extension
          ...
    def is_hidden_file_or_dir
          return False
```
```
class WinOS(BaseOS):
    def get_file_extension
          inherit
    def search_files
          inherit
    def count_files_by_extension
          inherit
    def is_hidden_file_or_dir
          overwrite
          part for Windows
```
```
class UnixOS(BaseOS):
    def get_file_extension
          inherit
    def search_files
          inherit
    def count_files_by_extension
          inherit
    def is_hidden_file_or_dir
          overwrite
          part for Unix
```
```
class MacOS(UnixOS):
    def get_file_extension
          inherit
    def search_files
          inherit
    def count_files_by_extension
          inherit
    def is_hidden_file_or_dir
          overwriting according to conditions specific to this platform,
          for example: consider /Volumes/MobileBackups as hidden
```
in main.py
```
import ...
if sys.platform.startswith('win'):
     current_os = WinOS()
elif sys.platform.startswith('linux') or platform_name.startswith('ios'):
     current_os = UnixOS()
elif sys.platform.startswith('darwin'):  # or check for certain version
     current_os = MacOS()
else:
     # undefined
     current_os = BaseOS()
```
Next, use the methods of the corresponding class.

**Comment by victordomingos** [comment]
Seems ok. I would rather move the platform detection code out of main.py. We can have a simple function that when called returns the class corresponding to the current platform. Or the import itself could take care of that automatically.
